import streamlit as st
st.title("Attendance at UoW")

faqs = {
    "What to do if you forget or lose your ID card, or if you have not received it at enrolment": "You should keep your ID card with you at all times while at the University. Attendance at on-campus classes is recorded by swiping your ID card on the reader in the teaching space no earlier than 15 minutes before the class start time and no later than 16 minutes before the class end time.\n\nIf you forget your ID card, you will not be able to register your attendance and will appear as absent. Temporary paper passes from reception cannot be used as evidence of attendance.\n\nIf you forget, lose, or have not received your ID card, make an absence note on SEA to indicate your absence was due to an inability to register attendance. This note does not change your status to attended but provides context for staff.\n\nTo add an absence, click the 'Add Absence' button in SEA. Further details are available in the SEA guide. If you need a replacement ID card, visit the Student ID cards page.",
    
    "What should I do if I am going to be absent from the University?": "If you cannot attend a class due to illness or unforeseen circumstances, log your absence and reason in SEA using the 'Add Absence' button. This helps us monitor engagement.\n\nFor prolonged absences (e.g., bereavement, serious illness), notify your Course Leader, Personal Tutor, and the Library and Student Centre Team or raise an enquiry on Compass.\n\nIf your situation impacts assessments, consider submitting a Mitigating Circumstances claim.",
    
    "What if I have swiped into a reader but my attendance has not recorded?": "A successful swipe should display a green tick and your student ID number on the reader.\n\nIf you saw both but attendance was not recorded, notify the Library and Student Centre Team or raise an enquiry on Compass.\n\nIf no green tick or ID appeared, your swipe was unsuccessful, and no record exists. In this case, add a note to your attendance record using the 'Add Absence' button, explaining you attended.\n\nYou may also ask your class tutor to manually mark your attendance, though this is at their discretion.",
    
    "What if I have logged into an activity in my module Blackboard site but my attendance has not recorded?": "If your log-in has not recorded, contact the Library and Student Centre Team or raise an enquiry on Compass.\n\nIf no log-in record is found, add a note to your attendance record in SEA using the 'Add Absence' button to indicate you engaged. The event will still show as an absence, but the reason will be noted.",
    
    "I have a Student Visa – how will the student engagement and attendance monitoring affect me?": "Regular attendance is a condition of your Student Visa. If you do not attend, the Visa Compliance Team will contact you for support.\n\nIf you fail to respond or continue missing classes, the University may withdraw sponsorship, leading to visa cancellation and course withdrawal.\n\nTo protect your visa, attend all scheduled classes and swipe your ID card. If you are absent for more than a day, notify the Library and Student Centre Team or raise an enquiry on Compass.\n\nUse SEA to log absences when unable to swipe in. This helps us track your attendance for UKVI purposes, and we will contact you if necessary.",
    
    "What will happen if my attendance is reviewed by my Personal Tutor?": "If you miss multiple scheduled classes, your Personal Tutor may contact you to check on your well-being and offer support. They can direct you to the right services, such as academic advice, student funding, or support from the Students' Union.\n\nContinued absences may lead to a formal review by your Personal Tutor, Course Team, and the Student Engagement and Attendance Team. Under University Regulations, students absent for 10 consecutive working days (two weeks) may be withdrawn from their course.\n\nIf you hold a Student Visa, the Visa Compliance Team will contact you if you miss classes.",
    
    "What can I do if I am withdrawn from my course due to non-attendance?": "If you hold a Student Visa and are withdrawn for non-attendance, contact the Visa Compliance Team immediately.\n\nIf you do not have a Student Visa and are withdrawn under University regulations, you may appeal the decision. Instructions on how to appeal will be included in your withdrawal notification email. You must submit a statement and supporting evidence within 10 working days.\n\nWithdrawals follow the standard interruption and withdrawal process. Your tuition fee liability depends on the withdrawal date, and Student Finance England will be notified, affecting funding eligibility. More details are available on the 'Interrupting or Withdrawing from Studies' page."
}

for question, answer in faqs.items():
    with st.expander(question):
        st.write(answer)